version: '3'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=ms-email
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./resources/db/migration:/docker-entrypoint-initdb.d